image: debian/buster
packages:
  - build-essential
  - curl
sources:
  - https://git.sr.ht/~vrischmann/kcm

tasks:
  - install_golang: |
      curl -L -O https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz
      tar -C /usr/local -xzf go1.13.5.linux-amd64.tar.gz
      echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.buildenv

  - setup: |
      cd kcm
      go mod download
      go mod verify

  - build: |
      cd kcm
      go build -v

triggers:
  - action: email
    condition: always
    to: "Vincent Rischmann <vincent@rischmann.fr>"
